### ISSUE TITLE
Verisure devices

### ISSUE THREAD

**Issue by IvovanTulden** [jdeluyck/verisure-domoticz#1]
Below are some additonals devices.
- Smoke is added to be complete.
- Voicebox information
- PIR2 is a PIR without camera function, the ones with camera I can't read. 
- Smartplugs and Controlpugs use the same ID, the look the same.

Hope you can do something with this.

"climateValues": [
       {
            "deviceType": "SMOKE2",
            "temperature": 15.2,
            "deviceLabel": "id fits here",
            "humidity": 72.0,
            "deviceArea": "Zolder",
            "time": "2018-01-29T17:06:14.000Z"
	},

        {
            "temperature": 16.0,
            "deviceType": "VOICEBOX1",
            "deviceArea": "Hal",
            "deviceLabel": "id fits here",
            "time": "2018-01-29T20:10:49.000Z"
        },
        {
            "temperature": 15.0,
            "deviceType": "PIR2",
            "deviceArea": "Garage",
            "deviceLabel": "id fits here",
            "time": "2018-01-29T20:04:01.000Z"
        }

 "smartPlugs": [
        {
            "isHazardous": false,
            "currentState": "ON",
            "deviceLabel": "id fits here",
            "pendingState": "NONE",
            "icon": "OTHER",
            "area": "Thuis"
        }
    ],
    "controlPlugs": [
        {
            "profile": "OTHER",
            "currentState": "ON",
            "area": "Thuis",
            "deviceId": "other id",
	}

**Comment by jdeluyck** [comment]
Thanks!

I guess the deviceLabel is also in the usual XXXX YYYY format?

**Comment by IvovanTulden** [comment]
Dear Jan, 

Yes that is correct. 

If you want more information / screenshots let me know. 

PS: do you have some tips for me about running your software on a
Raspberry Pi 3 Jessy, because it is missing module 'arrow'? 

---
Mvg,
 Ivo van Tulden 

Jan De Luyck schreef op 01-02-2018 18:52:

> Thanks! 
> 
> I guess the deviceLabel is also in the usual XXXX YYYY format? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/jdeluyck/verisure-domoticz/issues/1#issuecomment-362348035
[2]

**Comment by jdeluyck** [comment]
You should be able to just install python3-arrow - https://packages.debian.org/jessie/python3-arrow.

**Comment by jdeluyck** [comment]
Should be ok now in master branch.
