### ISSUE TITLE
Read only user less information

### ISSUE THREAD

**Issue by IvovanTulden** [jdeluyck/verisure-domoticz#2]
Within MyPages it is possible to give a user a access-level, I use this for creating a read-only user then only gets information from the system. 

When the user is 'beheerder/administrator' the scripts runs fine, but with 'minium' rights there is a slight bug. The totalSmsCount is not available for all users.

What is did is create a overview of all the information that the 'minimum' user is missing below.
Perhaps you can code a 'try' command for this?

{
    "controlPlugs": [
        {
            "currentState": "ON",
            "deviceLabel": "XXXX XXXX",
            "deviceId": "12345678",
            "pendingState": "NONE",
            "area": "Thuis",
            "profile": "OTHER"
        }
    ],
    "installationErrorList": [],
    "eventCounts": [],
    "totalSmsCount": 0,
    "heatPumps": [],
    "userTracking": {
        "installationStatus": "NOT_CONFIGURED"
    },
    "batteryProcess": {
        "active": false
    },
    "pendingChanges": 0,
    "smartCameras": [],
}

**Comment by jdeluyck** [comment]
I've updated the code to check if the values are available before trying to actually use them. Should fix this. Commit 7f6428be519c57303fe793e20f62c01b7998fb35
